spring:
  application:
    name: BookingCare
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  mail:
    username: ${mail.user}
    password: ${mail.password}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${kafka.port}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  web:
    resources:
      add-mappings: false
      #Khong tu anh xa tai nguyen tinh
logging:
  level:
    root: error
