spring:
  application:
    name: booking-server-query
  elasticsearch:
    username: ${elastic.username}
    password: ${elastic.password}
    uris: ${elastic.uris}
  data:
    elasticsearch:
      repositories:
        enabled: true
  kafka:
    bootstrap-servers: ${kafka.server}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
server:
  port: ${server.port}
  address: ${server.address}
  error:
    include-message: always

logging:
  level:
    root: error
